#include <R.h>
#include <Rinternals.h>
#include <R_ext/Rdynload.h>

/* C entry point */
extern SEXP vldaft_fit(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP,
                       SEXP, SEXP, SEXP, SEXP, SEXP, SEXP,
                       SEXP, SEXP, SEXP, SEXP, SEXP);

/* Rust entry point (generated by extendr) */
extern SEXP wrap__vldaft_fit_rust(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP,
                                  SEXP, SEXP, SEXP, SEXP, SEXP, SEXP,
                                  SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"vldaft_fit", (DL_FUNC) &vldaft_fit, 18},
    {"wrap__vldaft_fit_rust", (DL_FUNC) &wrap__vldaft_fit_rust, 18},
    {NULL, NULL, 0}
};

void R_init_vldaft(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
